export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const GET_ROBOTS_IS_PENDING = 'GET_ROBOTS_IS_PENDING';
export const GET_ROBOTS_WAS_SUCCESSFUl = 'GET_ROBOTS_WAS_SUCCESSFUl';
export const GET_ROBOTS_HAD_ERROR = 'GET_ROBOTS_HAD_ERROR';

export const GET_ROBOT_IS_PENDING = 'GET_ROBOT_IS_PENDING';
export const GET_ROBOT_WAS_SUCCESSFUL = 'GET_ROBOT_WAS_SUCCESSFUL';
export const GET_ROBOT_HAD_ERROR = 'GET_ROBOT_HAD_ERROR';